apiVersion: v1
kind: ConfigMap
metadata:
  name: bangla-portal-config
  namespace: default
data:
  DATABASE_URL: "postgresql://portal_user:portal_pass@172.30.200.171:5432/bangla_portal"
  DB_HOST: "172.30.200.171"
  #DB_HOST: "192.168.16.190"
  DB_USER: "portal_user"
  # OpenTelemetry variables
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.observability.svc.cluster.local:4317"
  OTEL_PYTHON_AUTO_INSTRUMENTATION_ENABLED: "true"

