apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sso-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: keycloak.test.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keycloak
            port:
              number: 8080

  - host: banglaportal.test.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            #name: app-a
            name: bangla-portal-svc
            port:
              number: 80

  - host: app-b.test.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: oauth2-proxy-app-b
            port:
              number: 80

