name: Deploy to Kubernetes

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  deploy-to-demosever:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Set timestamp-based IMAGE_TAG
      - name: Set Tag as Environment Variable
        run: echo "IMAGE_TAG=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      # 4. Build and push Docker image from demo folder
      - name: Build and push Docker image
        run: |
          docker build -f demo/Dockerfile -t ${DOCKER_USERNAME}/bangla_portal:${{ env.IMAGE_TAG }} demo
          docker push ${DOCKER_USERNAME}/bangla_portal:${{ env.IMAGE_TAG }}

      # 5. Get latest image tag (optional)
      - name: Get Latest Image Tag
        id: extract_tag
        run: |
          echo "::set-output name=tag::${{ env.IMAGE_TAG }}"

      # 6. Update Deployment YAML with new image (optional)
      - name: Update Deployment File
        run: |
          sed -i 's|image: ccrosscloud/bangla_portal:.*|image: ccrosscloud/bangla_portal:${{ steps.extract_tag.outputs.tag }}|g' k8/deployment.yaml

      # 7. Commit changes (optional)
      - name: Commit files
        run: |
          git config --local user.email "survivalmotivator@gmail.com"
          git config --local user.name "awscloude"
          git commit -am "Update image tag to $GITHUB_SHA" || echo "No changes to commit"

      # 8. Push changes back to main (optional)
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          #branch: main
          branch: ${{ github.ref }}
          github_token: ${{ secrets.PAT_TOKEN }}

