name: Build & Push Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout using PAT (required!)
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      # 2. Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4. Extract Tag
      - name: Extract Tag
        id: extract_tag
        run: echo "tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      # 5. Build & Push Image
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ccrosscloud/bangla_portal:${{ steps.extract_tag.outputs.tag }}

      # 6. Update Deployment YAML
      - name: Update Deployment File
        run: |
          sed -i 's|image: ccrosscloud/bangla_portal:.*|image: ccrosscloud/bangla_portal:${{ steps.extract_tag.outputs.tag }}|g' k8/deployment.yaml

      # 7. Commit changes
      - name: Commit files
        run: |
          git config --local user.email "survivalmdddotivator@gmail.com"
          git config --local user.name "awscloudssdsde"
          git add k8/deployment.yaml
          git commit -m "Update image tag to ${{ steps.extract_tag.outputs.tag }}" || echo "No changes to commit"

      # 8. Push changes using PAT
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          branch: main

